variables:
  PIPELINE_RUNNER: darkwind8/builder-docker-kubectl:v1.0.1

stages:
  - deploy-gitea

deploy-gitea:
  image: ${PIPELINE_RUNNER}
  stage: deploy-gitea
  script:
    - mkdir ~/.kube
    - echo "${kubectl_config}" > ~/.kube/config
    - cd k8s/gitea/files;
    - ./generate_ssl.sh
    - cd ..
    - python3 install.py --gitea_password="$gitea_password"